### ISSUE TITLE
Captcha not working because it uses the deprecated css_class attribute

### ISSUE THREAD

**Issue by soulchild** [gshank/html-formhandler#100]
The Captcha field type is not working, because it uses the deprecated css_class attribute:

    has '+css_class' => ( default => 'captcha' );

This fails with:

    Could not find an attribute by the name of 'css_class' to inherit from in HTML::FormHandler::Field::Captcha

**Comment by gshank** [comment]
Changed css_class to wrapper_calls. Did not test...
