### ISSUE TITLE
Github example link

### ISSUE THREAD

**Issue by gmambro** [gshank/html-formhandler#104]
The URL http://github.com:gshank/formhandler-example in HTML::FormHandler::Widget::Theme::Bootstrap3 should be http://github.com:gshank/formhandler-example

**Comment by gshank** [comment]
I think you mean there's a colon instead of a slash.

**Comment by gmambro** [comment]
You're right... I forgot to edit it!
BTW the example looks like is using Bootstrap instead if Bootstrap3.
