### ISSUE TITLE
Calling $form->clear() on a new form then $form->field('field name')->has_errors() causes exception in Moose.

### ISSUE THREAD

**Issue by rustyconover** [gshank/html-formhandler#88]
Exception is:

```
Cannot delegate has_errors to has_errors because the value of result is not defined at /Users/rconover/perl5/lib/perl5/darwin-2level/Moose/Meta/Method/Delegation.pm line 94
HTML::FormHandler::Field::has_errors('HTML::FormHandler::Field::Select::1=HASH(0x7fc6e4333448)') called at test-form.pl line 32
```

Tested version 0.40057 from CPAN.

Here is a script that causes the problem:

```perl
use strict;
use warnings;

package TestForm;
use HTML::FormHandler::Moose;
extends 'HTML::FormHandler';

has_field 'subscription_type' => (
    type => 'Select',
    widget => 'RadioGroup',
    required => 1,
    options => [
        {
            value => '1',
            label => 'test',
        },
        {
            value => '2',
            label => 'test',
        },
    ]
);

__PACKAGE__->meta->make_immutable;
no HTML::FormHandler::Moose;
1;

package main;

my $form = TestForm->new();
$form->clear();
$form->field('subscription_type')->has_errors();
```

If I don't clear the form, ```$field->has_errors()``` works fine.

**Comment by abraxxa** [comment]
I'd say it works as designed. What is your use case?

**Comment by rustyconover** [comment]
I'm caching the creation of the form object to prevent spending time in object creation in my request handler.  It can take like 150ms to create the form object.

In my handler if the request was via GET, I'm calling ```$form->clear()``` to reset the form which may have been previously used.

Then in my template I call ```$form->field('name').has_errors()``` to determine if I need to output the errors and divs surrounding then.   Doing that triggers this behavior.  Which causes :cry: sadness.

**Comment by abraxxa** [comment]
I tried that as well and failed because too much state isn't reset. In my case the performance penalty was about 500ms. A pull request with tests and a proposed fix is very welcome!

**Comment by rustyconover** [comment]
You probably mean too much state is reset right?  I think a fix would be looking at ```$form->clear()``` and have it call ```$form->processed()``` before it calls ```$form->clear_result()```.  But I may be wrong.

**Comment by gshank** [comment]
For persistent forms, you could call ->clear at the end of the request cycle (though it doesn't do much good, it does keep the data out of the persistent form object). You always need to do $form->process before doing anything; it will do the clear on your behalf. The clear will remove the chain of result objects, so lots of things won't work after that if you do it outside of a process call. (In particular, it makes no sense to do $form->clear and then $form->has_errors.) 

This is a matter of architecture at this point and can't really be changed.
