### ISSUE TITLE
widget_wrapper is readonly?

### ISSUE THREAD

**Issue by Altreus** [gshank/html-formhandler#96]
It seems a bit odd that I can't change the cosmetic appearance of the form before it's rendered. I can add the Widget role required to do so, but I can't tell the form to use it.

I don't want to tread on any toes, and I'm sure there are reasons why it's done this way, but it seems a bit overkill that I have to actually subclass a form to create one that renders differently. Until I actually come to render the form it seems like it should be possible to mutate as much of the properties used in rendering as I like - and if I do it afterwards, that's irrelevant anyway, because I already have the rendered HTML string.

Is there another way to do this at runtime? I'd like to avoid creating a class whose entire purpose is to override a single property.

**Comment by Altreus** [comment]
As an afterthought, it would be handy if the Widget classes came with FormHandler subclasses that applied them, but had defaults for everything else, e.g. an `HTML::FormHandler::Bootstrap3`, or suchlike, that just represented a form using `HTML::FormHandler::Widget::Wrapper::Bootstrap3` instead of `::Simple`

**Comment by gshank** [comment]
The wrapper is applied as a role to the form class. This means that you have a new anonymous class that's used to create the form object. It's not like the form can use the widget wrapper name to just access the code. It would have to be applied to the object instance using Moose's 'apply_all_roles'. If this is something that you want to do, there are a lot of places you can hook into to do it before rendering happens.

As far as HTML::FormHandler::Bootstrap3 etc classes, I recommend creating those yourself if you want them.
